restylers:
  - name:  astyle
    enabled: true
    arguments: ["--style=google","--indent-namespaces", "--indent-col1-comments"]
    include: 
      - "src/**/.hpp"
      - "src/**/.cpp"
      - "test/*.hpp"
      - "test/*.cpp"
  - name:  astyle
    enabled: true
    arguments: ["--style=attach","--indent=spaces=2", "--indent-col1-comments"]
    include: 
      - "examples/**/*.ino"
    