restylers:
  - name:  astyle
    enabled: true
    arguments: ["--style=google","--indent-namespaces", "--indent-col1-comments", "--recursive","*.hpp,*.cpp"]
  - name:  astyle
    enabled: true
    arguments: ["--style=attach","--indent=spaces=2", "--indent-col1-comments", "--recursive",examples/*.ino]
    