name: "release-candidate"

on:
  push:
    tags:
      - 'v*-rc*'

jobs:
  doxygen:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt install doxygen graphviz
    - name: generate docs
      run: doxygen
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: doc/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tagged-release:
    name: "Release candidate"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v1
      - name: install platform io
        run: | 
          pip3 install -U setuptools
          pip3 install -U wheel
          pip3 install -U platformio
          python3 -m platformio update

      - name: building examples and running the unit tests
        run: bash ./.scripts/ci_local.sh
        
      - name: Check code meets quality standards
        id: code-inspector
        uses: codeinspectorio/github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          code_inspector_access_key: ${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}
          code_inspector_secret_key: ${{ secrets.CODE_INSPECTOR_SECRET_KEY }}
          min_quality_grade: 'EXCELLENT'
          min_quality_score: '99'
          max_defects_rate: '0.01'
          max_complex_functions_rate: '0.01'
          max_long_functions_rate: '0.01'
          project_name: 'LedController'
          max_timeout_sec: '600'

      - name: pack repo
        run: |
          zip -r release.zip License README.md library.properties keywords.txt .vscode examples src
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            License
            release.zip
            
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: build-artifact-${{ matrix.os }}-${{ matrix.compiler }}
          path: .
